# CI/CD startup template v1.0
# Add this template to your project so that you can easily setup CI/CD on your project.
#
# This template contains the following features:
#   - Automatically triggers a build whenever new code is pushed to main, test, acceptance and production branches
#   - Automatically starts a release to the correct environement dependent on the branch that triggered the build
#

# BRANCHES THAT TRIGGER A BUILD
# Change the branch names (or add or remove branches) so that this fits your project
trigger:
 branches:
  include:
    - main
    - production

# PIPELINE VARIABLES
# Add here any variable that you need to use during the pipeline execution
variables:
- name: ASDatabaseName
  value: bla

# Branch names variables
# Change these variables to fit your project's needs  
- name: mainBranchName
  value: 'refs/heads/main'
  readonly: true
- name: productionBranchName
  value: 'refs/heads/production'
  readonly: true
  


stages:
# ------------------------------------------------------------------------
#                             DEPLOY
# ------------------------------------------------------------------------
# There is one stage per environement. Please remove the ones that do not apply
# to the current project

# ------- DEV -------
- stage: "Dev"
  displayName: "DEV"
  condition: eq(variables['Build.SourceBranch'], '${{ variables.mainBranchName }}')
  jobs:
    - deployment: Deploy
      environment: Dev
      displayName: "DEV"
      strategy:
        runOnce:
          deploy:
            steps:
              - task: PowerShell@2
                displayName: Install tabular editor
                inputs:
                  targetType: 'inline'
                  script: |
                    $TabularEditorDownloadUrl = "https://github.com/otykier/TabularEditor/releases/download/2.12.4/TabularEditor.Portable.zip" 
                    
                    $DownloadDest = join-path (get-location) "TabularEditor.zip"
                    
                    Invoke-WebRequest -Uri $TabularEditorDownloadUrl -OutFile $DownloadDest
                    
                    Expand-Archive -Path $DownloadDest -DestinationPath (get-location).Path
                    Remove-Item $DownloadDest
              - task: CmdLine@2
                displayName: Deploy Model
                inputs:
                  script: 'TabularEditor.exe "$(System.DefaultWorkingDirectory)/_TabularRepo/TabularModel/Model.bim" -D "$(ASConnectionString)" "$(ASDatabaseName)" -O -C -P -R -M -W -E -V'
